#!/bin/bash
# 02_ssb_sideways_pruning.sh — SSB LINEORDER sideways pruning
#
# Denormalizes LINEORDER with SUPPLIER, CUSTOMER, PART dimension tables,
# sorts by dimension attribute cardinality (ascending), and splits into
# equal-sized chunks for parallel GPU loading.
#
# Sort keys (cardinality ascending):
#   1. S_REGION    (card: 5)     col 18
#   2. C_REGION    (card: 5)     col 19
#   3. P_MFGR      (card: 5)     col 20
#   4. S_NATION    (card: 25)    col 21
#   5. C_NATION    (card: 25)    col 22
#   6. P_CATEGORY  (card: 25)    col 23
#   7. S_CITY      (card: 250)   col 24
#   8. C_CITY      (card: 250)   col 25
#   9. P_BRAND1    (card: 1000)  col 26
#  10. LO_ORDERDATE(card: 2556)  col 6 (numeric)
#
# Usage:
#   bash scripts/golap/02_ssb_sideways_pruning.sh
#
# Prerequisites:
#   - DuckDB installed
#   - SSB data generated by dbgen in /export/data1/ssb/input${SF}/

set -eu

SCRIPT_START=$(date +%s)
step_time() {
    local label="$1"
    local start="$2"
    local end=$(date +%s)
    local elapsed=$((end - start))
    echo "TIMING ${label}: ${elapsed}s ($(( elapsed / 60 ))m $(( elapsed % 60 ))s)"
}

# === CLI parsing ===
SF=100
NUM_SPLITS=$(nproc)
DELETE_INPUT=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        -s) SF="$2"; shift 2 ;;
        -n) NUM_SPLITS="$2"; shift 2 ;;
        --delete-input)
            # Delete input/lineorder after denormalize to reduce peak
            # storage. Required for SF>=500 on tight disks.
            DELETE_INPUT=1; shift ;;
        *)  echo "Usage: $0 [-s SF] [-n NUM_SPLITS] [--delete-input]" >&2; exit 1 ;;
    esac
done

# === Configuration ===
DATA_BASE="/export/data1/ssb"
INPUT_BASE_DIR="${DATA_BASE}/input${SF}"
LINEORDER_INPUT_DIR="${INPUT_BASE_DIR}/lineorder"
CUSTOMER_INPUT_DIR="${INPUT_BASE_DIR}/customer"
SUPPLIER_INPUT_DIR="${INPUT_BASE_DIR}/supplier"
PART_INPUT_DIR="${INPUT_BASE_DIR}/part"

OUTPUT_BASE_DIR="${DATA_BASE}/sideways/sf${SF}"
LINEORDER_OUTPUT_DIR="${OUTPUT_BASE_DIR}/lineorder"

SORT_INPUT_DIR="${OUTPUT_BASE_DIR}/tmp/sort_input/lineorder"
SORT_TMP_DIR="${OUTPUT_BASE_DIR}/tmp/sort"
DUCKDB_TMP_DIR="${OUTPUT_BASE_DIR}/tmp/duckdb"

DB_FILE=":memory:"

# Clear any leftover intermediate files from a previous aborted run so
# that split/rename never see stale numbering.
for d in "${SORT_INPUT_DIR}" "${SORT_TMP_DIR}" "${DUCKDB_TMP_DIR}"; do
    [ -d "${d}" ] && find "${d}" -mindepth 1 -delete 2>/dev/null || true
done

mkdir -p "${OUTPUT_BASE_DIR}" "${LINEORDER_OUTPUT_DIR}" \
         "${SORT_INPUT_DIR}" "${SORT_TMP_DIR}" "${DUCKDB_TMP_DIR}"

SORT_MEM="50%"
THREADS=$(nproc)
export LC_ALL=C

ensure_empty_dir() {
    local target_dir="$1"

    if [ ! -d "$target_dir" ]; then
        echo "Error: Directory '$target_dir' does not exist."
        return 0
    fi

    if [ -n "$(ls -A "$target_dir")" ]; then
        echo "Directory '${target_dir}' is not empty."
        read -p "Clean the directory? [y/N]: " CONFIRM

        case "$CONFIRM" in
            [yY][eE][sS]|[yY])
                echo "Cleaning directory..."
                find "$target_dir" -mindepth 1 -delete
                echo "Directory cleaned."
                echo "Please rerun the script."
                exit 0
                ;;
            *)
                echo "Operation aborted by user."
                exit 1
                ;;
        esac
    fi
}

ensure_empty_dir "${SORT_INPUT_DIR}"
ensure_empty_dir "${LINEORDER_OUTPUT_DIR}"

# ============================================================
# Step 1: Denormalize LINEORDER with DuckDB
# ============================================================
STEP1_START=$(date +%s)
echo "[Step 1] Generating denormalized LINEORDER data using DuckDB..."

duckdb "$DB_FILE" <<EOF
SET memory_limit = '128GB';
SET threads = ${THREADS};
SET temp_directory = '${DUCKDB_TMP_DIR}';

-- SSB table views
CREATE OR REPLACE VIEW lineorder AS
SELECT * FROM read_csv('${LINEORDER_INPUT_DIR}/lineorder.tbl*', delim='|', header=False,
    columns={
        'lo_orderkey': 'BIGINT',
        'lo_linenumber': 'INTEGER',
        'lo_custkey': 'INTEGER',
        'lo_partkey': 'INTEGER',
        'lo_suppkey': 'INTEGER',
        'lo_orderdate': 'INTEGER',
        'lo_orderpriority': 'VARCHAR',
        'lo_shippriority': 'VARCHAR',
        'lo_quantity': 'INTEGER',
        'lo_extendedprice': 'INTEGER',
        'lo_ordtotalprice': 'INTEGER',
        'lo_discount': 'INTEGER',
        'lo_revenue': 'INTEGER',
        'lo_supplycost': 'INTEGER',
        'lo_tax': 'INTEGER',
        'lo_commitdate': 'INTEGER',
        'lo_shipmode': 'VARCHAR'
    });

CREATE OR REPLACE VIEW supplier AS
SELECT * FROM read_csv('${SUPPLIER_INPUT_DIR}/supplier.tbl*', delim='|', header=False,
    columns={
        's_suppkey': 'INTEGER',
        's_name': 'VARCHAR',
        's_address': 'VARCHAR',
        's_city': 'VARCHAR',
        's_nation': 'VARCHAR',
        's_region': 'VARCHAR',
        's_phone': 'VARCHAR'
    });

CREATE OR REPLACE VIEW customer AS
SELECT * FROM read_csv('${CUSTOMER_INPUT_DIR}/customer.tbl*', delim='|', header=False,
    columns={
        'c_custkey': 'INTEGER',
        'c_name': 'VARCHAR',
        'c_address': 'VARCHAR',
        'c_city': 'VARCHAR',
        'c_nation': 'VARCHAR',
        'c_region': 'VARCHAR',
        'c_phone': 'VARCHAR',
        'c_mktsegment': 'VARCHAR'
    });

CREATE OR REPLACE VIEW part AS
SELECT * FROM read_csv('${PART_INPUT_DIR}/part.tbl*', delim='|', header=False,
    columns={
        'p_partkey': 'INTEGER',
        'p_name': 'VARCHAR',
        'p_mfgr': 'VARCHAR',
        'p_category': 'VARCHAR',
        'p_brand1': 'VARCHAR',
        'p_color': 'VARCHAR',
        'p_type': 'VARCHAR',
        'p_size': 'INTEGER',
        'p_container': 'VARCHAR'
    });

-- Denormalize: LINEORDER + SUPPLIER + CUSTOMER + PART
-- Original 17 columns + 9 sort keys + trailing delimiter
COPY (
    SELECT
        lo.lo_orderkey,        -- col 1
        lo.lo_linenumber,      -- col 2
        lo.lo_custkey,         -- col 3
        lo.lo_partkey,         -- col 4
        lo.lo_suppkey,         -- col 5
        lo.lo_orderdate,       -- col 6  (also sort key 10, numeric)
        lo.lo_orderpriority,   -- col 7
        lo.lo_shippriority,    -- col 8
        lo.lo_quantity,        -- col 9
        lo.lo_extendedprice,   -- col 10
        lo.lo_ordtotalprice,   -- col 11
        lo.lo_discount,        -- col 12
        lo.lo_revenue,         -- col 13
        lo.lo_supplycost,      -- col 14
        lo.lo_tax,             -- col 15
        lo.lo_commitdate,      -- col 16
        lo.lo_shipmode,        -- col 17

        -- Sort keys (cardinality ascending)
        s.s_region,            -- col 18 (card: 5)
        c.c_region,            -- col 19 (card: 5)
        p.p_mfgr,              -- col 20 (card: 5)
        s.s_nation,            -- col 21 (card: 25)
        c.c_nation,            -- col 22 (card: 25)
        p.p_category,          -- col 23 (card: 25)
        s.s_city,              -- col 24 (card: 250)
        c.c_city,              -- col 25 (card: 250)
        p.p_brand1,            -- col 26 (card: 1000)

        -- Trailing '|' for parser compatibility
        '' AS dummy
    FROM lineorder lo
    JOIN supplier s ON lo.lo_suppkey = s.s_suppkey
    JOIN customer c ON lo.lo_custkey = c.c_custkey
    JOIN part p     ON lo.lo_partkey = p.p_partkey
)
TO '${SORT_INPUT_DIR}'
(
    FORMAT CSV,
    DELIMITER '|',
    HEADER FALSE,
    PER_THREAD_OUTPUT true,
    QUOTE ''
);
EOF

step_time "Step1_DuckDB_denormalize" "${STEP1_START}"

if [ "${DELETE_INPUT}" -eq 1 ]; then
    # LINEORDER denorm CSV is now self-contained in ${SORT_INPUT_DIR}.
    # The raw dbgen lineorder/ directory is no longer needed. Dim tables
    # (customer, supplier, part, date) are preserved because they are
    # referenced by symlinks created in Step 3.
    echo "[--delete-input] removing ${LINEORDER_INPUT_DIR}"
    rm -rf "${LINEORDER_INPUT_DIR}"
fi

# ============================================================
# Step 2: Sort by cardinality keys and split into chunks
# ============================================================
STEP2_START=$(date +%s)
echo "[Step 2] Sorting LINEORDER data by cardinality keys..."

TOTAL_LINES=$(find "${SORT_INPUT_DIR}" -name "*.csv" -print0 | xargs -0 cat | wc -l)
LINES_PER_FILE=$(( (TOTAL_LINES + NUM_SPLITS - 1) / NUM_SPLITS ))

echo "  Total lines: ${TOTAL_LINES}"
echo "  Chunks: ${NUM_SPLITS}"
echo "  Lines per chunk: ${LINES_PER_FILE}"

sort -T "${SORT_TMP_DIR}" \
     -t '|' \
     -k 18,18 \
     -k 19,19 \
     -k 20,20 \
     -k 21,21 \
     -k 22,22 \
     -k 23,23 \
     -k 24,24 \
     -k 25,25 \
     -k 26,26 \
     -k 6,6n \
     --buffer-size="${SORT_MEM}" \
     --parallel="${THREADS}" \
     "${SORT_INPUT_DIR}"/*.csv \
| split -l "${LINES_PER_FILE}" \
        -d -a 4 \
        - \
        "${LINEORDER_OUTPUT_DIR}/lineorder.tbl."

# Rename 0-indexed to 1-indexed (lineorder.tbl.00 -> lineorder.tbl.1).
# Sort numerically and descending so the moves don't collide.
python3 <<EOF
import os
import glob

target_dir = "${LINEORDER_OUTPUT_DIR}"
pattern = os.path.join(target_dir, "lineorder.tbl.[0-9]*")

files = [f for f in glob.glob(pattern) if f.rsplit('.', 1)[1].isdigit()]
files.sort(key=lambda p: int(p.rsplit('.', 1)[1]), reverse=True)

for old_path in files:
    base_path, suffix = old_path.rsplit('.', 1)
    new_num = int(suffix) + 1
    new_path = f"{base_path}.{new_num}"
    os.rename(old_path, new_path)
    print(f"Renamed: {old_path} -> {new_path}")
EOF

# Clean up temporary files
find "${SORT_INPUT_DIR}" -mindepth 1 -delete
find "${SORT_TMP_DIR}" -mindepth 1 -delete
find "${DUCKDB_TMP_DIR}" -mindepth 1 -delete

step_time "Step2_sort_and_split" "${STEP2_START}"

# ============================================================
# Step 3: Symlink dimension tables
# ============================================================
echo "[Step 3] Creating symlinks for dimension tables..."

for table in customer supplier part date; do
    SRCDIR="${INPUT_BASE_DIR}/${table}"
    DSTDIR="${OUTPUT_BASE_DIR}/${table}"
    if [ -e "${DSTDIR}" ] || [ -L "${DSTDIR}" ]; then
        echo "  Skip: ${DSTDIR} already exists"
    else
        ln -s "${SRCDIR}" "${DSTDIR}"
        echo "  Created: ${DSTDIR} -> ${SRCDIR}"
    fi
done

echo "[Step 3] Done."
echo ""
echo "=== SSB sideways pruning complete ==="
echo "Output: ${OUTPUT_BASE_DIR}/"
echo "  lineorder/ : $(ls "${LINEORDER_OUTPUT_DIR}" | wc -l) chunks"
echo "  customer/  : symlink -> ${INPUT_BASE_DIR}/customer"
echo "  supplier/  : symlink -> ${INPUT_BASE_DIR}/supplier"
echo "  part/      : symlink -> ${INPUT_BASE_DIR}/part"
echo "  date/      : symlink -> ${INPUT_BASE_DIR}/date"

step_time "Total" "${SCRIPT_START}"
